// SPDX-License-Identifier: Apache-2.0
package com.swirlds.common.io.utility;

import static com.swirlds.common.io.utility.FileUtils.executeAndRename;
import static com.swirlds.common.test.fixtures.AssertionUtils.assertEventuallyTrue;
import static java.nio.file.Files.exists;
import static org.hiero.base.concurrent.interrupt.Uninterruptable.abortAndThrowIfInterrupted;
import static org.hiero.base.file.FileUtils.writeAndFlush;
import static org.hiero.consensus.concurrent.manager.AdHocThreadManager.getStaticThreadManager;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.swirlds.common.config.StateCommonConfig;
import com.swirlds.common.io.config.TemporaryFileConfig;
import com.swirlds.config.api.Configuration;
import com.swirlds.config.api.ConfigurationBuilder;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.concurrent.CountDownLatch;
import org.hiero.base.io.streams.SerializableDataInputStream;
import org.hiero.consensus.concurrent.framework.config.ThreadConfiguration;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

@DisplayName("FileUtils Tests")
class FileUtilsTests {

    private static final Configuration CONFIGURATION = ConfigurationBuilder.create()
            .withConfigDataType(TemporaryFileConfig.class)
            .withConfigDataType(StateCommonConfig.class)
            .build();

    /**
     * Temporary directory provided by JUnit
     */
    @TempDir
    Path testDirectory;

    @BeforeEach
    void beforeEach() throws IOException {
        LegacyTemporaryFileBuilder.overrideTemporaryFileLocation(testDirectory.resolve("tmp"));
    }

    @AfterEach
    void cleanup() {
        deleteDirContents(testDirectory.toFile().listFiles());
    }

    /**
     * Recursive delete method to delete all files and directories listed. Java is not able to delete a directory if it
     * has files in it, so recurse into the directory and delete all files there first before deleting the directory.
     */
    private void deleteDirContents(final File[] files) {
        if (files == null) {
            return;
        }
        for (final File file : files) {
            if (file.isDirectory()) {
                deleteDirContents(file.listFiles());
            }
            file.delete();
        }
    }

    @Test
    @DisplayName("executeAndRename() Auto Generated Tmp Dir Test")
    void executeAndRenameAutoGeneratedTmpDirTest() throws InterruptedException, IOException {
        final Path foo = testDirectory.resolve("foo");
        final Path data = foo.resolve("data.txt");

        final CountDownLatch startedLatch = new CountDownLatch(1);
        final CountDownLatch pauseLatch = new CountDownLatch(1);

        new ThreadConfiguration(getStaticThreadManager())
                .setExceptionHandler((thread, throwable) ->
                        System.out.println("executeAndRenameAutoGeneratedTmpDirTest exception: " + throwable))
                .setRunnable(() -> {
                    try {
                        executeAndRename(
                                foo,
                                (final Path directory) -> {
                                    final Path dataTmp = directory.resolve("data.txt");

                                    writeAndFlush(dataTmp, out -> {
                                        out.writeNormalisedString("foo");
                                        out.flush();
                                        startedLatch.countDown();

                                        abortAndThrowIfInterrupted(
                                                pauseLatch::await, "interrupted when waiting on latch");

                                        out.writeNormalisedString("bar");
                                    });
                                },
                                CONFIGURATION);
                    } catch (final IOException e) {
                        throw new UncheckedIOException(e);
                    }
                })
                .build(true);

        // Wait until writing has started
        startedLatch.await();

        assertFalse(exists(foo), "directory should not yet exist");

        pauseLatch.countDown();

        assertEventuallyTrue(() -> exists(foo), Duration.ofSeconds(2), "final directory does not exist");
        assertEventuallyTrue(() -> exists(data), Duration.ofSeconds(2), "final file does not exist");

        try (final SerializableDataInputStream in =
                new SerializableDataInputStream(new FileInputStream(data.toFile()))) {
            assertEquals("foo", in.readNormalisedString(100), "invalid data in file");
            assertEquals("bar", in.readNormalisedString(100), "invalid data in file");
        }
    }

    @Test
    @DisplayName("executeAndRename() Destination Exists Test")
    void executeAndRenameDestinationExistsTest() throws IOException {
        final Path foo = testDirectory.resolve("foo");

        // Creating this directory is expected to cause problems
        Files.createDirectories(foo);

        assertThrows(
                IOException.class,
                () -> executeAndRename(foo, null, CONFIGURATION),
                "existence of directory before hand should cause problems");
    }
}
