# SPDX-License-Identifier: Apache-2.0
balances.exportDir.path=data/accountBalances/
upgrade.artifacts.path=data/upgrade
contracts.chainId=298
contracts.maxGasPerSec=15000000000
contracts.maxGasPerSecBackend=15000000000
contracts.maxGasPerTransaction=15000000000
staking.periodMins=1
staking.fees.nodeRewardPercentage=10
staking.fees.stakingRewardPercentage=10
# Needed for Restart and Reconnect HapiTests that run many transactions of each type
bootstrap.throttleDefsJson.resource=genesis/throttles-dev.json
fees.createSimpleFeeSchedule=true
ledger.id=0x03
hedera.shard=0
hedera.realm=0
blockStream.streamMode=BOTH
nodes.enableDAB=true
blockStream.blockFileDir=data/blockStreams
blockStream.blockNodeConnectionFileDir=data/config
blockStream.buffer.bufferDirectory=data/block-buffer
hedera.recordStream.logDir=data/recordStreams
hedera.recordStream.wrappedRecordHashesDir=data/wrappedRecordHashes
hedera.profiles.active=DEV
grpc.nodeOperatorPortEnabled=true
# For CI tests we want to override roster weights from override-network.json
networkAdmin.preserveStateWeightsDuringOverride=false
contracts.systemContract.hts.addresses=359,364
contracts.evm.version=v0.67
#Enforce native lib verification to not halt node on dev env
contracts.evm.nativeLibVerification.halt.enabled=false
contracts.throttle.throttleByGas=true
contracts.opsDurationThrottleCapacity=500000000000000
contracts.opsDurationThrottleUnitsFreedPerSecond=500000000000000
# Since we use override-network.json in many @HapiTests, we need to disable PCES signature verification; otherwise,
# state signature txs over pre-upgrade hash H will poison ISS detection over the post-upgrade hash H' that results
# from applying the override roster during Hedera.onStateInitialized()
event.preconsensus.forceIgnorePcesSignatures=true
# Uncomment for testing TSS with :app:run
#tss.hintsEnabled=true
#tss.historyEnabled=true
#tss.wrapsEnabled=true
#tss.forceMockSignatures=false
# Uncomment an addition to TSS properties for exporting a network.json w/ TSS during :app:run
#networkAdmin.upgradeSysFilesLoc=<path-to-your-preferred-export-directory>
#networkAdmin.diskNetworkExport=ONLY_FREEZE_BLOCK
#networkAdmin.diskNetworkExportTss=true
