# SPDX-License-Identifier: Apache-2.0
name: "305: [FLOW] Generate Rel Notes"
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch, tag, or commit to build"
        required: false
        type: string
      version:
        description: "Release Version Number (ex: 0.59.2):"
        type: string
        required: true
      dry-run-enabled:
        description: "Perform Dry Run"
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  generate-release-notes-tag:
    name: Generate Release Notes (Tag)
    uses: ./.github/workflows/853-call-create-github-release.yaml
    if: ${{ github.event_name == 'push' }}
    with:
      ref: ${{ github.sha }}
      release-version: ${{ github.ref_name }}
      create-release-notes: true
      create-release: false
    secrets:
      gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}

  generate-release-notes-dispatch:
    name: Generate Release Notes (Workflow Dispatch)
    uses: ./.github/workflows/853-call-create-github-release.yaml
    if: ${{ github.event_name == 'workflow_dispatch' }}
    with:
      ref: ${{ inputs.ref || github.sha }}
      release-version: ${{ inputs.version || github.ref_name }}
      create-release-notes: true
      create-release: false
      dry-run: ${{ inputs.dry-run-enabled }}
    secrets:
      gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
