# SPDX-License-Identifier: Apache-2.0
name: "602: [FLOW] Merge Queue Controller"
on:
  push:
    branches:
      - trunk-merge/**
  # Added workflow dispatch for testing purposes
  workflow_dispatch:

permissions:
  id-token: write
  actions: write
  pull-requests: write
  statuses: write
  checks: write
  contents: write

jobs:
  # Trigger the MATS Tests
  extract-jdk-version:
    name: Extract Java Version
    uses: ./.github/workflows/854-call-extract-jdk-version.yaml
    with:
      ref: ${{ github.ref }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  extract-citr-vars:
    name: Extract CITR Vars
    uses: ./.github/workflows/855-call-extract-citr-vars.yaml
    with:
      ref: ${{ github.ref }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  trigger-mats-tests:
    name: MQ MATS
    needs:
      - extract-jdk-version
    uses: ./.github/workflows/800-call-mats-tests.yaml
    with:
      ref: ${{ github.ref }}
      enable-snyk-scan: "true" # for Snyk
      enable-gradle-determinism: "true"
      enable-docker-determinism: "true"
      java-version: ${{ needs.extract-jdk-version.outputs.jdk-version }}
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      codacy-project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      snyk-token: ${{ secrets.SNYK_TOKEN }}

  # Trigger the MQ XTS Tests
  trigger-merge-queue-xts-tests:
    name: MQ XTS
    needs:
      - extract-jdk-version
      - extract-citr-vars
    uses: ./.github/workflows/815-call-xts-tests.yaml
    with:
      ref: ${{ github.ref }}
      branch-name: ${{ github.ref_name }}
      solo-version: ${{ needs.extract-citr-vars.outputs.citr-solo-version }}
      solo-ge-0440: "true"
      helm-release-name: "mirror-1"
      custom-job-label: "Merge Queue XTS:"
      enable-timing-sensitive-test-suite: "true"
      enable-hammer-test-suite: "true"
      enable-hapi-test-suite: "true"
      enable-otter-test-suite: "true"
      enable-hedera-node-jrs-panel: "true"
      enable-sdk-tck-regression-panel: "true"
      java-version: ${{ needs.extract-jdk-version.outputs.jdk-version }}

    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      platform-access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      regression-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      slack-citr-details-token: ${{ secrets.SLACK_CITR_DETAILED_REPORTS_WEBHOOK }}
      slack-tck-report-webhook: ${{ secrets.SLACK_TCK_MONITOR_WEBHOOK }}

  # Trigger the MQ Performance/Longevity Tests
  trigger-merge-queue-performance-tests:
    name: MQPT
    needs:
      - extract-jdk-version
      - extract-citr-vars
    uses: ./.github/workflows/830-call-merge-queue-performance-test.yaml
    with:
      test-asset: "${{ needs.extract-citr-vars.outputs.mqpt-cluster }}"
      ref: "${{ github.ref }}"
      solo-version: "${{ needs.extract-citr-vars.outputs.citr-solo-version }}"
      nlg-accounts: "20000000"
      nlg-time: "60"
      add-app-props: ""
      add-settings: ""
      run_NLGDparams: "-Dbenchmark.stepDuration=20m -Dbenchmark.coolDown=3m"
      delete-namespace: true
      java-version: "${{ needs.extract-jdk-version.outputs.jdk-version }}"
    secrets:
      slack-report-webhook: ${{ secrets.SLACK_CITR_DETAILED_REPORTS_WEBHOOK }}
      rootly-api-token: ${{ secrets.ROOTLY_API_TOKEN }}
